version: '3'
services:
  builder_builroot:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile_builder
      args:
        UID: 1000
        USER: builder
        ARCH: armv8
        IMAGE: debian:latest
    container_name: builder_buildroot
    ports:
      - "2022:22"
    volumes:
      - ./docker-data/images-v8:/home/${USER}/output/image
