ARG IMAGE
FROM ${IMAGE}

ARG UID=1000
ARG USER=builder
ARG ARCH

RUN useradd -m -u ${UID} -s /bin/bash ${USER}

# Non-interactive configuration of tzdata
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update
RUN apt-get install -y cmake openssh-server mc libncurses-dev g++ wget cpio rsync bc patch

USER ${USER}
RUN mkdir -p /home/${USER}/.ssh
RUN mkdir -p /home/${USER}/config
COPY docker-configs/id_rsa_builder.pub /home/${USER}/.ssh/authorized_keys

# mount config
ADD buildroot /home/${USER}/buildroot
COPY docker-configs/sipeed_licheepi_zero_ex_defconfig /home/${USER}/buildroot/configs/

WORKDIR /home/${USER}/buildroot

USER root
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]